language: rust

os: linux
dist: xenial
rust: stable
sudo: required

addons:
  apt:
    packages:
      - clang
      - libreadline-dev

before_script:
  python3 ./script/epics/load.py &&
  ./script/epics/build.sh

script:
  source ./script/epics/env.sh &&
  python3 ./script/build.py &&
  python3 ./script/test.py
