[package]
name = "device_support"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
epics_binding = { path = "../binding" }

[profile.dev]
incremental = false

[profile.release]
incremental = false
